train_input:
    train_path: 'data/moses_train_small.csv'
    val_path: 'data/moses_val_small.csv'
    batch_size: 50
    exts: ['.src', '.trg']
    fields: [SRC, TGT]
    shuffle: True

eval_input:
    eval_path: 'data/moses_test_small.csv'
    exts: ['.src', '.trg']
    fields: [SRC, TGT]

model:
    d_model: 512
    nhead: 8
    num_encoder_layers: 6
    num_decoder_layers: 6
    dim_feedforward: 2048
    dropout: 0.1
    activation: 'relu'

optimizer:
    optimizer_type: 'adam'
    learning_rate: 0.0001
    loss_scaling_factor: 1.0

runconfig:
    max_steps: 100000
    checkpoint_steps: 1000
    log_steps: 100
    seed: 42
    model_dir: "./model_dir"
    save_losses: true
