train_input:
    train_path: 'data_small/moses_train_small.csv'
    val_path: 'data_small/moses_val_small.csv'
    batch_size: 50000
    exts: ['.src', '.trg']
    fields: [SRC, TGT]
    shuffle: True

eval_input:
    eval_path: 'data_small/moses_test_small.csv'
    exts: ['.src', '.trg']
    fields: [SRC, TGT]

model:
    name: "transmol"
    mixed_precision: True
    dropout: 0.1
    activation_fn: "relu"

optimizer:
    optimizer_type: 'adam'
    learning_rate: 0.0
    beta1: 0.9
    beta2: 0.98
    eps: 0.000000001

runconfig:
    max_steps: 50
    checkpoint_steps: 4
    log_steps: 1
    seed: 42
    model_dir: "./model_dir"
    save_losses: true
